package com.sakanal.cma.pojo;

import java.util.List;

public class College {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_college.id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_college.college_name
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    private String collegeName;

    private List<Major> major;

    public List<Major> getMajor() {
        return major;
    }

    public void setMajor(List<Major> major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_college.id
     *
     * @return the value of cma_college.id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_college.id
     *
     * @param id the value for cma_college.id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_college.college_name
     *
     * @return the value of cma_college.college_name
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public String getCollegeName() {
        return collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_college.college_name
     *
     * @param collegeName the value for cma_college.college_name
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName == null ? null : collegeName.trim();
    }

    @Override
    public String toString() {
        return "College{" +
                "id=" + id +
                ", collegeName='" + collegeName + '\'' +
                ", major=" + major +
                '}';
    }
}