package com.sakanal.cma.pojo;

public class Major {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_major.id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_major.major_name
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    private String majorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_major.college_id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    private Integer collegeId;

    private String collegeName;

    public String getCollegeName() {
        return collegeName;
    }

    public void setCollegeName(String collegeName) {
        this.collegeName = collegeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_major.id
     *
     * @return the value of cma_major.id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_major.id
     *
     * @param id the value for cma_major.id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_major.major_name
     *
     * @return the value of cma_major.major_name
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public String getMajorName() {
        return majorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_major.major_name
     *
     * @param majorName the value for cma_major.major_name
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public void setMajorName(String majorName) {
        this.majorName = majorName == null ? null : majorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_major.college_id
     *
     * @return the value of cma_major.college_id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public Integer getCollegeId() {
        return collegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_major.college_id
     *
     * @param collegeId the value for cma_major.college_id
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    public void setCollegeId(Integer collegeId) {
        this.collegeId = collegeId;
    }

    @Override
    public String toString() {
        return "Major{" +
                "id=" + id +
                ", majorName='" + majorName + '\'' +
                ", collegeId=" + collegeId +
                ", collegeName='" + collegeName + '\'' +
                '}';
    }
}