package com.sakanal.cma.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.validation.constraints.Email;
import javax.validation.constraints.Past;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import java.sql.Date;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_id
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    private Long stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_name
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    @Pattern(regexp = "(^[a-zA-Z0-9_-]{6,16}$)|(^[\\u2E80-\\u9FFF]{2,5}$)",
            message = "请输入2-5位中文或者6-16位英文和数字的组合")
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_password
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    @Pattern(regexp = "^[a-zA-Z0-9_-]{6,18}$",
            message = "请输入6-18位英文和数字的组合")
    private String stuPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_gender
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    private String stuGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_phone
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    private Long stuPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_birthday
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    @Past
    private Date stuBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_address
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    private String stuAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_email
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    @Email(message = "邮箱格式不正确")
    private String stuEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_class
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    private String stuClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_college
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    private String stuCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_student.stu_major
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    private String stuMajor;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_id
     *
     * @return the value of cma_student.stu_id
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public Long getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_id
     *
     * @param stuId the value for cma_student.stu_id
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuId(Long stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_name
     *
     * @return the value of cma_student.stu_name
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_name
     *
     * @param stuName the value for cma_student.stu_name
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_password
     *
     * @return the value of cma_student.stu_password
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuPassword() {
        return stuPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_password
     *
     * @param stuPassword the value for cma_student.stu_password
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuPassword(String stuPassword) {
        this.stuPassword = stuPassword == null ? null : stuPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_gender
     *
     * @return the value of cma_student.stu_gender
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_gender
     *
     * @param stuGender the value for cma_student.stu_gender
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender == null ? null : stuGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_phone
     *
     * @return the value of cma_student.stu_phone
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public Long getStuPhone() {
        return stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_phone
     *
     * @param stuPhone the value for cma_student.stu_phone
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuPhone(Long stuPhone) {
        this.stuPhone = stuPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_birthday
     *
     * @return the value of cma_student.stu_birthday
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public Date getStuBirthday() {
        return stuBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_birthday
     *
     * @param stuBirthday the value for cma_student.stu_birthday
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuBirthday(Date stuBirthday) {
        this.stuBirthday = stuBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_address
     *
     * @return the value of cma_student.stu_address
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuAddress() {
        return stuAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_address
     *
     * @param stuAddress the value for cma_student.stu_address
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuAddress(String stuAddress) {
        this.stuAddress = stuAddress == null ? null : stuAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_email
     *
     * @return the value of cma_student.stu_email
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuEmail() {
        return stuEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_email
     *
     * @param stuEmail the value for cma_student.stu_email
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuEmail(String stuEmail) {
        this.stuEmail = stuEmail == null ? null : stuEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_class
     *
     * @return the value of cma_student.stu_class
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuClass() {
        return stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_class
     *
     * @param stuClass the value for cma_student.stu_class
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuClass(String stuClass) {
        this.stuClass = stuClass == null ? null : stuClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_college
     *
     * @return the value of cma_student.stu_college
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuCollege() {
        return stuCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_college
     *
     * @param stuCollege the value for cma_student.stu_college
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuCollege(String stuCollege) {
        this.stuCollege = stuCollege == null ? null : stuCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_student.stu_major
     *
     * @return the value of cma_student.stu_major
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public String getStuMajor() {
        return stuMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_student.stu_major
     *
     * @param stuMajor the value for cma_student.stu_major
     *
     * @mbggenerated Sat Mar 26 16:07:10 CST 2022
     */
    public void setStuMajor(String stuMajor) {
        this.stuMajor = stuMajor == null ? null : stuMajor.trim();
    }


    @Override
    public String toString() {
        return "Student{" +
                "stuId=" + stuId +
                ", stuName='" + stuName + '\'' +
                ", stuPassword='" + stuPassword + '\'' +
                ", stuGender='" + stuGender + '\'' +
                ", stuPhone=" + stuPhone +
                ", stuBirthday=" + stuBirthday +
                ", stuAddress='" + stuAddress + '\'' +
                ", stuEmail='" + stuEmail + '\'' +
                ", stuClass='" + stuClass + '\'' +
                ", stuCollege='" + stuCollege + '\'' +
                ", stuMajor='" + stuMajor + '\'' +
                '}';
    }
}