package com.sakanal.cma.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.sql.Date;

public class Teacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_id
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private Integer tchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_name
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private String tchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_password
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private String tchPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_gender
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private String tchGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_phone
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private Long tchPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_birthday
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date tchBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_address
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private String tchAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_email
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private String tchEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cma_teacher.tch_college
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    private String tchCollege;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_id
     *
     * @return the value of cma_teacher.tch_id
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public Integer getTchId() {
        return tchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_id
     *
     * @param tchId the value for cma_teacher.tch_id
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchId(Integer tchId) {
        this.tchId = tchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_name
     *
     * @return the value of cma_teacher.tch_name
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public String getTchName() {
        return tchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_name
     *
     * @param tchName the value for cma_teacher.tch_name
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchName(String tchName) {
        this.tchName = tchName == null ? null : tchName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_password
     *
     * @return the value of cma_teacher.tch_password
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public String getTchPassword() {
        return tchPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_password
     *
     * @param tchPassword the value for cma_teacher.tch_password
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchPassword(String tchPassword) {
        this.tchPassword = tchPassword == null ? null : tchPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_gender
     *
     * @return the value of cma_teacher.tch_gender
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public String getTchGender() {
        return tchGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_gender
     *
     * @param tchGender the value for cma_teacher.tch_gender
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchGender(String tchGender) {
        this.tchGender = tchGender == null ? null : tchGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_phone
     *
     * @return the value of cma_teacher.tch_phone
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public Long getTchPhone() {
        return tchPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_phone
     *
     * @param tchPhone the value for cma_teacher.tch_phone
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchPhone(Long tchPhone) {
        this.tchPhone = tchPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_birthday
     *
     * @return the value of cma_teacher.tch_birthday
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public Date getTchBirthday() {
        return tchBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_birthday
     *
     * @param tchBirthday the value for cma_teacher.tch_birthday
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchBirthday(Date tchBirthday) {
        this.tchBirthday = tchBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_address
     *
     * @return the value of cma_teacher.tch_address
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public String getTchAddress() {
        return tchAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_address
     *
     * @param tchAddress the value for cma_teacher.tch_address
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchAddress(String tchAddress) {
        this.tchAddress = tchAddress == null ? null : tchAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_email
     *
     * @return the value of cma_teacher.tch_email
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public String getTchEmail() {
        return tchEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_email
     *
     * @param tchEmail the value for cma_teacher.tch_email
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchEmail(String tchEmail) {
        this.tchEmail = tchEmail == null ? null : tchEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cma_teacher.tch_college
     *
     * @return the value of cma_teacher.tch_college
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public String getTchCollege() {
        return tchCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cma_teacher.tch_college
     *
     * @param tchCollege the value for cma_teacher.tch_college
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setTchCollege(String tchCollege) {
        this.tchCollege = tchCollege == null ? null : tchCollege.trim();
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "tchId=" + tchId +
                ", tchName='" + tchName + '\'' +
                ", tchPassword='" + tchPassword + '\'' +
                ", tchGender='" + tchGender + '\'' +
                ", tchPhone=" + tchPhone +
                ", tchBirthday=" + tchBirthday +
                ", tchAddress='" + tchAddress + '\'' +
                ", tchEmail='" + tchEmail + '\'' +
                ", tchCollege='" + tchCollege + '\'' +
                '}';
    }
}