package com.sakanal.cma.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TeacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public TeacherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andTchIdIsNull() {
            addCriterion("tch_id is null");
            return (Criteria) this;
        }

        public Criteria andTchIdIsNotNull() {
            addCriterion("tch_id is not null");
            return (Criteria) this;
        }

        public Criteria andTchIdEqualTo(Integer value) {
            addCriterion("tch_id =", value, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdNotEqualTo(Integer value) {
            addCriterion("tch_id <>", value, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdGreaterThan(Integer value) {
            addCriterion("tch_id >", value, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("tch_id >=", value, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdLessThan(Integer value) {
            addCriterion("tch_id <", value, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdLessThanOrEqualTo(Integer value) {
            addCriterion("tch_id <=", value, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdIn(List<Integer> values) {
            addCriterion("tch_id in", values, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdNotIn(List<Integer> values) {
            addCriterion("tch_id not in", values, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdBetween(Integer value1, Integer value2) {
            addCriterion("tch_id between", value1, value2, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchIdNotBetween(Integer value1, Integer value2) {
            addCriterion("tch_id not between", value1, value2, "tchId");
            return (Criteria) this;
        }

        public Criteria andTchNameIsNull() {
            addCriterion("tch_name is null");
            return (Criteria) this;
        }

        public Criteria andTchNameIsNotNull() {
            addCriterion("tch_name is not null");
            return (Criteria) this;
        }

        public Criteria andTchNameEqualTo(String value) {
            addCriterion("tch_name =", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameNotEqualTo(String value) {
            addCriterion("tch_name <>", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameGreaterThan(String value) {
            addCriterion("tch_name >", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameGreaterThanOrEqualTo(String value) {
            addCriterion("tch_name >=", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameLessThan(String value) {
            addCriterion("tch_name <", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameLessThanOrEqualTo(String value) {
            addCriterion("tch_name <=", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameLike(String value) {
            addCriterion("tch_name like", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameNotLike(String value) {
            addCriterion("tch_name not like", value, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameIn(List<String> values) {
            addCriterion("tch_name in", values, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameNotIn(List<String> values) {
            addCriterion("tch_name not in", values, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameBetween(String value1, String value2) {
            addCriterion("tch_name between", value1, value2, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchNameNotBetween(String value1, String value2) {
            addCriterion("tch_name not between", value1, value2, "tchName");
            return (Criteria) this;
        }

        public Criteria andTchPasswordIsNull() {
            addCriterion("tch_password is null");
            return (Criteria) this;
        }

        public Criteria andTchPasswordIsNotNull() {
            addCriterion("tch_password is not null");
            return (Criteria) this;
        }

        public Criteria andTchPasswordEqualTo(String value) {
            addCriterion("tch_password =", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordNotEqualTo(String value) {
            addCriterion("tch_password <>", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordGreaterThan(String value) {
            addCriterion("tch_password >", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("tch_password >=", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordLessThan(String value) {
            addCriterion("tch_password <", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordLessThanOrEqualTo(String value) {
            addCriterion("tch_password <=", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordLike(String value) {
            addCriterion("tch_password like", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordNotLike(String value) {
            addCriterion("tch_password not like", value, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordIn(List<String> values) {
            addCriterion("tch_password in", values, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordNotIn(List<String> values) {
            addCriterion("tch_password not in", values, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordBetween(String value1, String value2) {
            addCriterion("tch_password between", value1, value2, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchPasswordNotBetween(String value1, String value2) {
            addCriterion("tch_password not between", value1, value2, "tchPassword");
            return (Criteria) this;
        }

        public Criteria andTchGenderIsNull() {
            addCriterion("tch_gender is null");
            return (Criteria) this;
        }

        public Criteria andTchGenderIsNotNull() {
            addCriterion("tch_gender is not null");
            return (Criteria) this;
        }

        public Criteria andTchGenderEqualTo(String value) {
            addCriterion("tch_gender =", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderNotEqualTo(String value) {
            addCriterion("tch_gender <>", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderGreaterThan(String value) {
            addCriterion("tch_gender >", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderGreaterThanOrEqualTo(String value) {
            addCriterion("tch_gender >=", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderLessThan(String value) {
            addCriterion("tch_gender <", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderLessThanOrEqualTo(String value) {
            addCriterion("tch_gender <=", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderLike(String value) {
            addCriterion("tch_gender like", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderNotLike(String value) {
            addCriterion("tch_gender not like", value, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderIn(List<String> values) {
            addCriterion("tch_gender in", values, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderNotIn(List<String> values) {
            addCriterion("tch_gender not in", values, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderBetween(String value1, String value2) {
            addCriterion("tch_gender between", value1, value2, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchGenderNotBetween(String value1, String value2) {
            addCriterion("tch_gender not between", value1, value2, "tchGender");
            return (Criteria) this;
        }

        public Criteria andTchPhoneIsNull() {
            addCriterion("tch_phone is null");
            return (Criteria) this;
        }

        public Criteria andTchPhoneIsNotNull() {
            addCriterion("tch_phone is not null");
            return (Criteria) this;
        }

        public Criteria andTchPhoneEqualTo(Long value) {
            addCriterion("tch_phone =", value, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneNotEqualTo(Long value) {
            addCriterion("tch_phone <>", value, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneGreaterThan(Long value) {
            addCriterion("tch_phone >", value, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneGreaterThanOrEqualTo(Long value) {
            addCriterion("tch_phone >=", value, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneLessThan(Long value) {
            addCriterion("tch_phone <", value, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneLessThanOrEqualTo(Long value) {
            addCriterion("tch_phone <=", value, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneIn(List<Long> values) {
            addCriterion("tch_phone in", values, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneNotIn(List<Long> values) {
            addCriterion("tch_phone not in", values, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneBetween(Long value1, Long value2) {
            addCriterion("tch_phone between", value1, value2, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchPhoneNotBetween(Long value1, Long value2) {
            addCriterion("tch_phone not between", value1, value2, "tchPhone");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayIsNull() {
            addCriterion("tch_birthday is null");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayIsNotNull() {
            addCriterion("tch_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("tch_birthday =", value, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("tch_birthday <>", value, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("tch_birthday >", value, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tch_birthday >=", value, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("tch_birthday <", value, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("tch_birthday <=", value, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("tch_birthday in", values, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("tch_birthday not in", values, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tch_birthday between", value1, value2, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("tch_birthday not between", value1, value2, "tchBirthday");
            return (Criteria) this;
        }

        public Criteria andTchAddressIsNull() {
            addCriterion("tch_address is null");
            return (Criteria) this;
        }

        public Criteria andTchAddressIsNotNull() {
            addCriterion("tch_address is not null");
            return (Criteria) this;
        }

        public Criteria andTchAddressEqualTo(String value) {
            addCriterion("tch_address =", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressNotEqualTo(String value) {
            addCriterion("tch_address <>", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressGreaterThan(String value) {
            addCriterion("tch_address >", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressGreaterThanOrEqualTo(String value) {
            addCriterion("tch_address >=", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressLessThan(String value) {
            addCriterion("tch_address <", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressLessThanOrEqualTo(String value) {
            addCriterion("tch_address <=", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressLike(String value) {
            addCriterion("tch_address like", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressNotLike(String value) {
            addCriterion("tch_address not like", value, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressIn(List<String> values) {
            addCriterion("tch_address in", values, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressNotIn(List<String> values) {
            addCriterion("tch_address not in", values, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressBetween(String value1, String value2) {
            addCriterion("tch_address between", value1, value2, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchAddressNotBetween(String value1, String value2) {
            addCriterion("tch_address not between", value1, value2, "tchAddress");
            return (Criteria) this;
        }

        public Criteria andTchEmailIsNull() {
            addCriterion("tch_email is null");
            return (Criteria) this;
        }

        public Criteria andTchEmailIsNotNull() {
            addCriterion("tch_email is not null");
            return (Criteria) this;
        }

        public Criteria andTchEmailEqualTo(String value) {
            addCriterion("tch_email =", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailNotEqualTo(String value) {
            addCriterion("tch_email <>", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailGreaterThan(String value) {
            addCriterion("tch_email >", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailGreaterThanOrEqualTo(String value) {
            addCriterion("tch_email >=", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailLessThan(String value) {
            addCriterion("tch_email <", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailLessThanOrEqualTo(String value) {
            addCriterion("tch_email <=", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailLike(String value) {
            addCriterion("tch_email like", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailNotLike(String value) {
            addCriterion("tch_email not like", value, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailIn(List<String> values) {
            addCriterion("tch_email in", values, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailNotIn(List<String> values) {
            addCriterion("tch_email not in", values, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailBetween(String value1, String value2) {
            addCriterion("tch_email between", value1, value2, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchEmailNotBetween(String value1, String value2) {
            addCriterion("tch_email not between", value1, value2, "tchEmail");
            return (Criteria) this;
        }

        public Criteria andTchCollegeIsNull() {
            addCriterion("tch_college is null");
            return (Criteria) this;
        }

        public Criteria andTchCollegeIsNotNull() {
            addCriterion("tch_college is not null");
            return (Criteria) this;
        }

        public Criteria andTchCollegeEqualTo(String value) {
            addCriterion("tch_college =", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeNotEqualTo(String value) {
            addCriterion("tch_college <>", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeGreaterThan(String value) {
            addCriterion("tch_college >", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeGreaterThanOrEqualTo(String value) {
            addCriterion("tch_college >=", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeLessThan(String value) {
            addCriterion("tch_college <", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeLessThanOrEqualTo(String value) {
            addCriterion("tch_college <=", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeLike(String value) {
            addCriterion("tch_college like", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeNotLike(String value) {
            addCriterion("tch_college not like", value, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeIn(List<String> values) {
            addCriterion("tch_college in", values, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeNotIn(List<String> values) {
            addCriterion("tch_college not in", values, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeBetween(String value1, String value2) {
            addCriterion("tch_college between", value1, value2, "tchCollege");
            return (Criteria) this;
        }

        public Criteria andTchCollegeNotBetween(String value1, String value2) {
            addCriterion("tch_college not between", value1, value2, "tchCollege");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cma_teacher
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 02 16:49:11 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cma_teacher
     *
     * @mbggenerated Sat Apr 02 16:49:11 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}