package com.sakanal.cma.dao;

import com.sakanal.cma.pojo.College;
import com.sakanal.cma.pojo.CollegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int countByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int deleteByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int insert(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int insertSelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    List<College> selectByExample(CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    College selectCollegeByPrimaryKey(Integer id);

    String selectCollegeNameByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByExample(@Param("record") College record, @Param("example") CollegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByPrimaryKeySelective(College record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_college
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByPrimaryKey(College record);
}