package com.sakanal.cma.dao;

import com.sakanal.cma.pojo.Major;
import com.sakanal.cma.pojo.MajorExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MajorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int countByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int deleteByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int insert(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int insertSelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    List<Major> selectByExample(MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    Major selectByPrimaryKey(Integer id);

    List<Major> selectMajorByCollegeId(Integer id);

    String selectMajorNameByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByExampleSelective(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByExample(@Param("record") Major record, @Param("example") MajorExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByPrimaryKeySelective(Major record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cma_major
     *
     * @mbggenerated Mon Mar 28 22:00:27 CST 2022
     */
    int updateByPrimaryKey(Major record);
}